### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by JasonGross** [tchajed/coq-tricks#1]
`nil` means `@nil _`.  You might be interested in multiple argument lists; `eq_refl` means `@eq_refl _ _`, `eq_refl a` means `@eq_refl _ a`.

**Comment by tchajed** [comment]
I meant for nil to be an example of where it would be inconvenient if the type argument were not maximally inserted. That happened due to `Set Implicit Arguments` and that was when I first realized when you should care about whether or not something is maximally inserted.

How do you specify multiple argument lists? I recall looking for them and not quite finding an example in the documentation.

**Comment by JasonGross** [comment]
Oh, right, this was the thing I had to look in the standard library to learn how to do.  https://github.com/coq/coq/blob/trunk/theories/Init/Logic.v#L291

**Comment by tchajed** [comment]
Thanks, I added a reference and improved the explanation in 447da7053.
