### ISSUE TITLE
Introduce categories for tricks?

### ISSUE THREAD

**Issue by anton-trunov** [tchajed/coq-tricks#6]
Do you think it makes sense to categorize the tricks?
Something like this:

- Pattern matching tricks
- Induction principles and destruction
- Totality and termination
- Rewriting
- Existential variables management (better name?)
- Notations
- Ltac tricks
- Search tricks
- Implicit arguments
- ???

**Comment by tchajed** [comment]
Makes sense, now that the list is a bit longer. I've split up the tricks into Ltac and Gallina (and a small section on querying Coq, which should really be expanded).

I don't want to have too many categories since I've always intended this list to be read exhaustively and quickly. Are there a few useful distinctions you think should be made within the Ltac section in particular?

**Comment by anton-trunov** [comment]
Hmm it's hard to say, because now the Ltac category fits into one screen 😄 
Probably `Ltac programming` vs `Proof tricks`.
But unless I'm missing something there is only one entry (`lazymatch`) in the first subcategory.
Feel free to close the issue, btw! And thanks for the cleanup!

**Comment by tchajed** [comment]
Cool, I'll close the issue for now and reconsider if we manage to grow the list considerably.
